### PR TITLE
Runtime: use node18.x

### PR DESCRIPTION
**Pull request by mrjimenez**

### CODE REVIEW

**Comment by mrjimenez** [comment]
Hold on, this is still not working:

```log
[22:41:37.671] 🐘 Downloading PHP runtime files
[22:41:37.673] 🐘 Installing Composer dependencies [START]
[22:41:37.693] PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /vercel/path0/.vercel/builders/node_modules/@libphp/amazon-linux-2-v74/native/php/modules/swoole (/vercel/path0/.vercel/builders/node_modules/@libphp/amazon-linux-2-v74/native/php/modules/swoole: cannot open shared object file: No such file or directory), /vercel/path0/.vercel/builders/node_modules/@libphp/amazon-linux-2-v74/native/php/modules/swoole.so (libcares.so.2: cannot open shared object file: No such file or directory)) in Unknown on line 0
[22:41:38.032] [4.0MiB/0.09s] Installing dependencies from lock file
```

Seems like a problem in `@libphp/amazon-linux-2-v74`. Any ideas how to fix it?

**Comment by f3l1x** [comment]
Hi @mrjimenez, I can drop swoole extension from `@libphp/amazon-linux-2-v74`. WDYT?

**Comment by mrjimenez** [comment]
Hi @f3l1x ,

I was thinking that maybe I could add the missing dependency, but still I don't understand why it stopped working.

I tried to put something like `"installCommand" : "yum install c-ares c-ares-devel -y",` in the vercel.json of my project, but it didn't work.

If I understood it correctly, `libswoole.so` is complaining that it cannot find `libcares.so.2`, but since the Amazon Linux image is the same, I see no obvious reason for that to happen.

Thank you for your attention and best regards!

**Comment by mrjimenez** [comment]
> Hi @mrjimenez, I can drop swoole extension from `@libphp/amazon-linux-2-v74`. WDYT?

Hi @f3l1x , I am having some difficulties to make it work. I tried to remove swoole.so, but I could not manage it. If you drop it from the image, I can test it.

Also, if you want to try it, my original idea was something like this, but I was not able to test it:

```diff
diff --git a/libs/amazon-linux-2-v74/Makefile b/libs/amazon-linux-2-v74/Makefile
index 76e6bdd..a366528 100644
--- a/libs/amazon-linux-2-v74/Makefile
+++ b/libs/amazon-linux-2-v74/Makefile
@@ -33,6 +33,8 @@ dist: build
        # Run new one PHP container
        docker run -it -d --name ${DOCKER_CONTAINER} ${DOCKER_IMAGE} /bin/bash
 
+       docker exec ${DOCKER_CONTAINER} /bin/yum install c-ares -y
+
        # Copy composer, php, php-cgi, php-fpm binaries
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/bin/composer > ${DIST_PHP_PATH}/composer
        docker exec ${DOCKER_CONTAINER} /bin/cat /opt/remi/php${DIST_PHP}/root/usr/bin/php > ${DIST_PHP_PATH}/php
@@ -106,6 +108,7 @@ dist: build
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libbz2.so.1 > ${DIST_LIB_PATH}/libbz2.so.1
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libcap-ng.so.0 > ${DIST_LIB_PATH}/libcap-ng.so.0
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libc-client.so.2007 > ${DIST_LIB_PATH}/libc-client.so.2007
+       docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libcares.so.2 > ${DIST_LIB_PATH}/libcares.so.2
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libcrypt.so.1 > ${DIST_LIB_PATH}/libcrypt.so.1
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libcurl.so.4 > ${DIST_LIB_PATH}/libcurl.so.4
        docker exec ${DOCKER_CONTAINER} /bin/cat /usr/lib64/libedit.so.0 > ${DIST_LIB_PATH}/libedit.so.0

```

**Comment by Case-Me** [comment]
Hi,

Just adding some context for documentation. Sorry, I think I should have started with that:

```bash
github/vercel-examples/php-7.4 git:(master ✔) $ vercel      
Vercel CLI 32.5.6
? Set up and deploy “~/github/vercel-examples/php-7.4”? [Y/n] y

...

🔗  Linked to projects/php-7-4 (created .vercel)
🔍  Inspect: ... [2s]
✅  Preview: ... [2s]
Error: The Runtime "vercel-php@0.3.3" is using "nodejs14.x", which is discontinued. Please upgrade your Runtime to a more recent version or consult the author for more details.
```

**Comment by mrjimenez** [comment]
Hi,

Just adding some context for documentation. Sorry, I think I should have started with that:

```bash
github/vercel-examples/php-7.4 git:(master ✔) $ vercel      
Vercel CLI 32.5.6
? Set up and deploy “~/github/vercel-examples/php-7.4”? [Y/n] y

...

🔗  Linked to projects/php-7-4 (created .vercel)
🔍  Inspect: ... [2s]
✅  Preview: ... [2s]
Error: The Runtime "vercel-php@0.3.3" is using "nodejs14.x", which is discontinued. Please upgrade your Runtime to a more recent version or consult the author for more details.
```

**Comment by f3l1x** [comment]
Resolved https://github.com/vercel-community/php/commit/f09c7684ab15b8666a76fde68498099cad70fcb5

**Pull request closed without merging**
